### ISSUE TITLE
Problems with target is position:relative

### ISSUE THREAD

**Issue by michelgallant** [tdoherty/jQuery.SpinJS#1]
Hi came upon a problem when the target was positioned relative. Plugin was positioned wrong.
This fixed it for me
Likes 56-57 changed to
    'top': $this.css('position') === 'absolute' || $this.css('position') === 'relative' ? 0 : $this.position().top - 1,
    'left': $this.css('position') === 'absolute' || $this.css('position') === 'relative' ? 0 : $this.position().left,

**Comment by tdoherty** [comment]
Please feel free to open a PR, would be much appreciated!

**Comment by tdoherty** [comment]
Fixed by https://github.com/tdoherty/jQuery.SpinJS/commit/8c4d107ae91878487fe0a620170a41b1635c0e09
